name: Accounts Module Deployment

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: ${{ github.ref_name }}

    steps:
      - name: Get Runner Public IP Address
        uses: candidob/get-runner-ip@v1.0.0
        id: ip

      - uses: actions/checkout@v4

      - name: Create remote directory if it doesn't exist
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_SERVER_IP || vars.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER || vars.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_KEY || vars.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            mkdir -p $HOME/mlm_demo/${{ github.event.repository.name }}

      - name: Archive code into zip
        run: |
          zip -r code.zip .

      - name: Upload zip file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_SERVER_IP || vars.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER || vars.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_KEY || vars.SSH_KEY }}
          source: "code.zip"
          target: "$HOME/mlm_demo/${{ github.event.repository.name }}/"

      - name: Deploy code on Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_SERVER_IP || vars.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER || vars.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_KEY || vars.SSH_KEY }}
          command_timeout: 15m
          port: 22
          script: |
            cd $HOME/mlm_demo/${{ github.event.repository.name }}/
            shopt -s extglob
            rm -rf -- !(code.zip|./app/configs/.env)
            unzip code.zip
            rm code.zip
            cp $HOME/mlm_demo/.gateway_env app/configs/.env

      - name: Run Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_SERVER_IP || vars.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER || vars.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_KEY || vars.SSH_KEY }}
          command_timeout: 15m
          port: 22
          script_stop: true
          script: |
            cd $HOME/mlm_demo/${{ github.event.repository.name }}
            docker compose stop
            docker compose up -d --build --force-recreate
